# Generated by Django 4.1 on 2022-09-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('apart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rec.apartlist')),
            ],
        ),
        migrations.DeleteModel(
            name='Rec',
        ),
    ]
