# Generated by Django 4.1 on 2022-09-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0003_priceinfo_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApartList',
            new_name='Apartments',
        ),
    ]
