# Generated by Django 4.1 on 2022-09-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_rename_apartlist_apartments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceinfo',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='per_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='apart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_info', to='rec.apartments'),
        ),
    ]
